services:
  mysql:
    image: mysql:8.0
    container_name: shortener-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  redis:
    image: redis:7
    container_name: shortener-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
